#!/usr/bin/env bash

function get_git_root()
{
    local repo

    IFS=' ' read -r -a array <<< "$@"

    repo=${array[-1]}
    repo=${repo##*/}
    repo=${repo%%.*}
    realpath "${repo}"
}

function main()
{
   if [[ $1 == "clone" ]]; then
      shift
      command git clone "$@"

      root=$(get_git_root "$@")
      command post-clone "$root"
   else
      command git "$@";
   fi;
}

main "$@"
