#!/usr/bin/env bash

function get_git_root()
{
    local repo

    IFS=' ' read -r -a array <<< "$@"

    if [[ ${#array[@]} == 1 ]]; then
        repo=${array[0]}
        repo=${repo##*/}
        repo=${repo%%.*}
    else
        repo=${array[1]}
    fi
    realpath "${repo}"
}

function main()
{
   if [[ $1 == "clone" ]]; then
      shift
      command git clone "$@"

      root=$(get_git_root "$@")
      command post-clone "$root"
   else
      command git "$@";
   fi;
}

main "$@"
